# Generated by Django 5.1.4 on 2025-12-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='register',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
