# Generated by Django 5.1.4 on 2025-12-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0002_appointment_register_alter_appointment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessassessment',
            name='status',
            field=models.CharField(choices=[('initiate', 'Initiate'), ('inprogress', 'In Progress'), ('completed', 'Completed'), ('default', 'Default')], default='initiate', max_length=20),
        ),
    ]
