# Generated by Django 5.1.4 on 2025-12-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0003_fitnessassessment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('initiate', 'Initiate'), ('inprogress', 'In Progress'), ('completed', 'Completed'), ('default', 'Default')], default='initiate', max_length=20),
        ),
    ]
