# Generated by Django 5.1.4 on 2025-12-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0004_consultation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='emp_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessassessment',
            name='emp_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
