# Generated by Django 5.1.4 on 2025-12-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0005_alter_consultation_emp_no_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together=set(),
        ),
    ]
