# Generated by Django 5.1.4 on 2025-12-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0006_alter_consultation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=255),
        ),
    ]
