# Generated by Django 5.1.4 on 2025-12-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0007_alter_employee_details_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='status',
            field=models.CharField(default='Active', max_length=255),
        ),
    ]
