# Generated by Django 5.2 on 2025-12-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0008_alter_employee_details_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacymedicine',
            name='chemical_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacymedicine',
            name='dose_volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacymedicine',
            name='medicine_form',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Creams', 'Creams'), ('Lotions', 'Lotions'), ('Powder', 'Powder'), ('Respules', 'Respules'), ('Drops', 'Drops'), ('Fluids', 'Fluids'), ('Other', 'Other'), ('SutureAndProcedureItems', 'SutureAndProcedureItems'), ('Dressing Items', 'Dressing Items')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacystock',
            name='chemical_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacystock',
            name='dose_volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacystock',
            name='medicine_form',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Creams', 'Creams'), ('Drops', 'Drops'), ('Fluids', 'Fluids'), ('Other', 'Other'), ('Lotions', 'Lotions'), ('Powder', 'Powder'), ('Respules', 'Respules'), ('SutureAndProcedureItems', 'SutureAndProcedureItems'), ('Dressing Items', 'Dressing Items')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacystockhistory',
            name='chemical_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacystockhistory',
            name='dose_volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacystockhistory',
            name='medicine_form',
            field=models.CharField(max_length=50),
        ),
    ]
