# Generated by Django 5.1.4 on 2025-12-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0009_alter_pharmacymedicine_chemical_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('initiate', 'Initiate'), ('inprogress', 'In Progress'), ('completed', 'Completed'), ('default', 'Default'), ('pending', 'Pending')], default='initiate', max_length=20),
        ),
    ]
