# Generated by Django 5.1.4 on 2025-12-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0011_alter_fitnessassessment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulanceconsumables',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='discardedmedicine',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='wardconsumables',
            name='total_quantity',
        ),
    ]
