# Generated by Django 5.1.4 on 2025-12-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0012_remove_ambulanceconsumables_total_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form17',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form27',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form38',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form39',
            name='mrdNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
