# Generated by Django 5.1.4 on 2025-12-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0014_remove_autoimmunetest_ana_reference_range_from_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form39',
        ),
    ]
