# Generated by Django 5.1.4 on 2025-12-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0015_delete_form39'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form39',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('mrdNo', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_no', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=225, null=True)),
                ('serialNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('workerName', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('proposedEmploymentDate', models.DateField(blank=True, null=True)),
                ('jobOccupation', models.CharField(blank=True, max_length=255, null=True)),
                ('rawMaterialHandled', models.CharField(blank=True, max_length=255, null=True)),
                ('medicalExamDate', models.DateField(blank=True, null=True)),
                ('medicalExamResult', models.CharField(blank=True, max_length=255, null=True)),
                ('certifiedFit', models.CharField(blank=True, choices=[('fit', 'Fit'), ('unfit', 'Unfit'), ('conditional', 'Conditional')], max_length=20, null=True)),
                ('certifyingSurgeonSignature', models.TextField(blank=True, null=True)),
                ('departmentSection', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
