# Generated by Django 5.1.4 on 2025-12-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0016_form39'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='member',
            name='emp_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='mail_id_Office',
            field=models.EmailField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='member',
            name='mail_id_Personal',
            field=models.EmailField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_Office',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_Personal',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='member',
            name='aadhar',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='designation',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='member',
            name='job_nature',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
