# Generated by Django 5.1.4 on 2026-01-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0017_remove_member_email_remove_member_employee_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiryregister',
            name='medicine_form',
            field=models.CharField(max_length=255),
        ),
    ]
