# Generated by Django 5.1.4 on 2026-01-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsw', '0018_alter_expiryregister_medicine_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiryregister',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expiryregister',
            name='chemical_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expiryregister',
            name='dose_volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expiryregister',
            name='medicine_form',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
