# Generated by Django 5.1.4 on 2026-01-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='followup_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='other_register',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='other_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
