# Generated by Django 5.1.5 on 2026-01-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pharmacystock_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='amount_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pharmacystockhistory',
            name='amount_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
