# Generated by Django 5.1.5 on 2026-01-22 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_dashboard_followup_type_dashboard_other_register_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidConsumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('medicine_form', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=255)),
                ('chemical_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dose_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('consumed_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlucoseConsumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('medicine_form', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=255)),
                ('chemical_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dose_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('consumed_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
