# Generated by Django 5.1.5 on 2026-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_firstaidconsumables_glucoseconsumables'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucoseconsumables',
            name='aadhar',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
