# Generated by Django 5.1.5 on 2026-01-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_glucoseconsumables_aadhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glucoseconsumables',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='glucoseconsumables',
            name='chemical_name',
        ),
        migrations.RemoveField(
            model_name='glucoseconsumables',
            name='dose_volume',
        ),
        migrations.RemoveField(
            model_name='glucoseconsumables',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='glucoseconsumables',
            name='medicine_form',
        ),
    ]
